package repl

import (
	"github.com/chzyer/readline"
)

// NewCompleter creates the command completer for tab completion.
func NewCompleter() *readline.PrefixCompleter {
	return readline.NewPrefixCompleter(
		// Session commands
		readline.PcItem("connect"),
		readline.PcItem("disconnect"),
		readline.PcItem("status"),

		// Account commands
		readline.PcItem("accounts",
			readline.PcItem("list",
				readline.PcItem("--safe="),
				readline.PcItem("--search="),
				readline.PcItem("--limit="),
				readline.PcItem("--offset="),
			),
			readline.PcItem("get"),
			readline.PcItem("create",
				readline.PcItem("--safe="),
				readline.PcItem("--platform="),
				readline.PcItem("--address="),
				readline.PcItem("--username="),
				readline.PcItem("--secret="),
				readline.PcItem("--name="),
			),
			readline.PcItem("delete"),
			readline.PcItem("password",
				readline.PcItem("--reason="),
			),
			readline.PcItem("change"),
			readline.PcItem("verify"),
			readline.PcItem("reconcile"),
			readline.PcItem("activities"),
		),

		// Safe commands
		readline.PcItem("safes",
			readline.PcItem("list",
				readline.PcItem("--search="),
				readline.PcItem("--limit="),
				readline.PcItem("--include-accounts"),
			),
			readline.PcItem("get"),
			readline.PcItem("create",
				readline.PcItem("--description="),
				readline.PcItem("--cpm="),
				readline.PcItem("--retention="),
			),
			readline.PcItem("update",
				readline.PcItem("--description="),
				readline.PcItem("--cpm="),
			),
			readline.PcItem("delete"),
			readline.PcItem("members"),
			readline.PcItem("add-member",
				readline.PcItem("--safe="),
				readline.PcItem("--member="),
				readline.PcItem("--role=",
					readline.PcItem("user"),
					readline.PcItem("admin"),
					readline.PcItem("auditor"),
				),
			),
			readline.PcItem("remove-member",
				readline.PcItem("--safe="),
				readline.PcItem("--member="),
			),
		),

		// User commands
		readline.PcItem("users",
			readline.PcItem("list",
				readline.PcItem("--search="),
				readline.PcItem("--type="),
				readline.PcItem("--limit="),
			),
			readline.PcItem("get"),
			readline.PcItem("create",
				readline.PcItem("--password="),
				readline.PcItem("--type=",
					readline.PcItem("EPVUser"),
					readline.PcItem("CPM"),
					readline.PcItem("PSM"),
					readline.PcItem("PVWA"),
				),
				readline.PcItem("--description="),
				readline.PcItem("--email="),
			),
			readline.PcItem("delete"),
			readline.PcItem("activate"),
			readline.PcItem("reset-password",
				readline.PcItem("--user="),
				readline.PcItem("--password="),
			),
		),

		// Platform commands
		readline.PcItem("platforms",
			readline.PcItem("list",
				readline.PcItem("--search="),
				readline.PcItem("--active"),
				readline.PcItem("--inactive"),
				readline.PcItem("--type="),
				readline.PcItem("--system="),
			),
			readline.PcItem("get"),
			readline.PcItem("activate"),
			readline.PcItem("deactivate"),
			readline.PcItem("duplicate",
				readline.PcItem("--id="),
				readline.PcItem("--name="),
				readline.PcItem("--description="),
			),
			readline.PcItem("export",
				readline.PcItem("--output="),
			),
			readline.PcItem("delete"),
		),

		// PSM monitoring commands
		readline.PcItem("psm",
			readline.PcItem("sessions",
				readline.PcItem("--from="),
				readline.PcItem("--to="),
				readline.PcItem("--safe="),
				readline.PcItem("--search="),
				readline.PcItem("--limit="),
			),
			readline.PcItem("live",
				readline.PcItem("--search="),
				readline.PcItem("--limit="),
			),
			readline.PcItem("get"),
			readline.PcItem("terminate"),
			readline.PcItem("suspend"),
			readline.PcItem("resume"),
			readline.PcItem("activities"),
			readline.PcItem("properties"),
		),

		// Health commands
		readline.PcItem("health",
			readline.PcItem("check"),
			readline.PcItem("components"),
			readline.PcItem("detail"),
			readline.PcItem("summary"),
		),

		// Settings commands
		readline.PcItem("set",
			readline.PcItem("output",
				readline.PcItem("table"),
				readline.PcItem("json"),
				readline.PcItem("yaml"),
			),
		),
		readline.PcItem("config",
			readline.PcItem("default-server"),
			readline.PcItem("default-auth",
				readline.PcItem("cyberark"),
				readline.PcItem("ldap"),
				readline.PcItem("radius"),
				readline.PcItem("windows"),
			),
			readline.PcItem("output",
				readline.PcItem("table"),
				readline.PcItem("json"),
				readline.PcItem("yaml"),
			),
			readline.PcItem("history-size"),
			readline.PcItem("insecure-ssl",
				readline.PcItem("true"),
				readline.PcItem("false"),
			),
			readline.PcItem("timeout"),
		),

		// Utility commands
		readline.PcItem("help",
			readline.PcItem("accounts"),
			readline.PcItem("safes"),
			readline.PcItem("users"),
			readline.PcItem("platforms"),
			readline.PcItem("psm"),
			readline.PcItem("health"),
			readline.PcItem("connect"),
			readline.PcItem("disconnect"),
			readline.PcItem("status"),
			readline.PcItem("set"),
			readline.PcItem("config"),
		),
		readline.PcItem("history"),
		readline.PcItem("clear"),
		readline.PcItem("exit"),
		readline.PcItem("quit"),
	)
}
